Repository Ming119/110-1_Database-System_Project, pull requests merged in 2021-11, with the labels that each got.

#11 Fixing some bugs after merged
  app/controllers/productController.py
  app/forms/NewCategory.py
  app/models/Product.py
  app/models/ProductCategory.py
  app/templates/index.html
  app/templates/product.html
Labels: enhancement

#12 Delete Category function
  app/controllers/indexController.py
  app/controllers/productController.py
  app/models/Product.py
  app/models/ProductCategory.py
  app/routes/productRoute.py
  app/templates/index.html
  app/templates/product.html
Labels: documentation, enhancement

#13 [UIR-06] MMS page for admin (updated [Security] MMS page access control #10)
  app/__init__.py
  app/controllers/manageUserController.py
  app/controllers/userController.py
  app/routes/manageUserRoute.py
  app/routes/userRoute.py
  app/templates/base.html
  app/util.py
  setup.sh
Labels: enhancement, security

#15 MMS - Delete User
  .gitignore
  app/__init__.py
  app/controllers/indexController.py
  app/controllers/productController.py
  app/controllers/userController.py
  app/forms/NewCategory.py
  app/forms/RegisterForm.py
  app/models/CustomerAddress.py
  app/models/CustomerPayment.py
  app/models/Discount.py
  app/models/Order.py
  app/models/Product.py
  app/models/ProductCategory.py
  app/models/ShoppingCart.py
  app/models/User.py
  app/routes/userRoute.py
  app/static/css/style.css
  app/templates/base.html
  app/templates/index.html
  app/templates/manageProduct.html
  app/templates/manageUser.html
  app/templates/productDetails.html
  app/templates/register.html
  app/templates/user.html
  app/templates/userProfile.html
  app/util.py
  requirements.txt
  tests/RobotTests/FeatureTests.robot
  tests/RobotTests/FeatureTests/UIR-03_Login/UIR-03_Login.robot
  tests/RobotTests/FeatureTests/UIR-03_Login/UIR-03_Login.txt
  tests/RobotTests/FeatureTests/UIR-04_Register/UIR-04_Register.robot
  tests/RobotTests/FeatureTests/UIR-04_Register/UIR-04_Register.txt
  tests/RobotTests/Keywords/common.txt
  tests/RobotTests/Keywords/flash.txt
  tests/RobotTests/Keywords/forgotPasswordPage.txt
  tests/RobotTests/Keywords/indexPage.txt
  tests/RobotTests/Keywords/loginPage.txt
  tests/RobotTests/Keywords/manageProductPage.txt
  tests/RobotTests/Keywords/registerPage.txt
  tests/RobotTests/Variables/common.txt
  tests/RobotTests/Variables/forgotPasswordPage.txt
  tests/RobotTests/Variables/indexPage.txt
  tests/RobotTests/Variables/loginPage.txt
  tests/RobotTests/Variables/manageProductPage.txt
  tests/RobotTests/Variables/registerPage.txt
  tests/RobotTests/allKeywords.txt
  tests/RobotTests/allVariables.txt
Labels: enhancement
