Repository Ming119/110-1_Database-System_Project, pull requests merged in 2021-12, with the labels that each got.

#17 [Refactor]
  app/controllers/indexController.py
  app/controllers/productController.py
  app/controllers/userController.py
  app/forms/NewCategoryForm.py
  app/forms/NewProductForm.py
  app/forms/RegisterForm.py
  app/forms/SearchForm.py
  app/forms/__init__.py
  app/models/Comment.py
  app/models/User.py
  app/models/__init__.py
  app/routes/__init__.py
  app/routes/indexRoute.py
  app/routes/productRoute.py
  app/routes/userRoute.py
  app/templates/base.html
  app/templates/forgotPassword.html
  app/templates/index.html
  app/templates/login.html
  app/templates/manageProduct.html
  app/templates/productDetails.html
  app/templates/register.html
  app/templates/resetPassword.html
  app/util.py
Labels: enhancement

#19 [Refactor] Fix Model Structure
  app/models/CustomerAddress.py
  app/models/CustomerPayment.py
  app/models/Discount.py
  app/models/Order.py
  app/models/Product.py
  app/models/ProductCategory.py
  app/models/ShoppingCart.py
  app/models/User.py
  app/models/__init__.py
Labels: enhancement, Back-end

#20 Nav Bar
  app/static/images/moonbird.png
  app/templates/base.html
Labels: enhancement, Front-end

#18 Create New User by Admin
  app/controllers/userController.py
  app/forms/NewUserForm.py
  app/forms/__init__.py
  app/routes/userRoute.py
  app/templates/manageUser.html
  app/templates/newUser.html
Labels: enhancement, Admin

#21 Updating User By Admin
  app/controllers/indexController.py
  app/controllers/productController.py
  app/controllers/userController.py
  app/forms/AddToCardForm.py
  app/forms/NewProductForm.py
  app/forms/UpdateProfileForm.py
  app/forms/__init__.py
  app/models/CustomerAddress.py
  app/models/User.py
  app/routes/userRoute.py
  app/templates/manageProduct.html
  app/templates/manageUser.html
  app/templates/productDetails.html
  app/templates/updateProfile.html
  app/templates/userProfile.html
Labels: enhancement, Back-end, Admin

#24 finish updata logo
  app/static/images/moonbird.png
Labels: Front-end

#23 delete product
  app/controllers/productController.py
  app/forms/__init__.py
  app/templates/base.html
  app/templates/manageUser.html
  app/templates/productDetails.html
Labels: enhancement, Front-end, Staff

#25 Staff DMS
  app/__init__.py
  app/controllers/discountController.py
  app/controllers/productController.py
  app/controllers/userController.py
  app/models/Discount.py
  app/models/Product.py
  app/models/User.py
  app/routes/__init__.py
  app/routes/discountRoute.py
  app/routes/userRoute.py
  app/templates/base.html
  app/templates/createDiscount.html
  app/templates/manageDiscount.html
  app/templates/manageUser.html
  app/templates/updateDiscount.html
  app/templates/userProfile.html
Labels: enhancement, Back-end, Staff

#26 Register Page Front-end Testing
  app/forms/RegisterForm.py
  app/templates/register.html
  app/util.py
  tests/RobotTests/FeatureTests.robot
  tests/RobotTests/Keywords/common.txt
  tests/RobotTests/Keywords/flash.txt
  tests/RobotTests/Keywords/forgotPassword.txt
  tests/RobotTests/Keywords/index.txt
  tests/RobotTests/Keywords/login.txt
  tests/RobotTests/Keywords/manageProduct.txt
  tests/RobotTests/Keywords/register.txt
  tests/RobotTests/Keywords/registerPage.txt
  tests/RobotTests/Variables/forgotPassword.txt
  tests/RobotTests/Variables/index.txt
  tests/RobotTests/Variables/login.txt
  tests/RobotTests/Variables/manageProduct.txt
  tests/RobotTests/Variables/register.txt
  tests/RobotTests/allKeywords.txt
  tests/RobotTests/allVariables.txt
Labels: Front-end, Customer, Testing

#27 MMS page Activate/Deactivate an account, Filter and Search function
  app/controllers/indexController.py
  app/controllers/userController.py
  app/models/User.py
  app/routes/userRoute.py
  app/templates/manageUser.html
  app/util.py
Labels: Back-end, Front-end, Admin

#28 Customer Add To Cart
  app/controllers/indexController.py
  app/controllers/productController.py
  app/forms/AddToCardForm.py
  app/forms/NewProductForm.py
  app/models/Product.py
  app/models/ProductCategory.py
  app/models/ShoppingCart.py
  app/models/User.py
  app/static/css/js
  app/static/js/productDetails.js
  app/templates/base.html
  app/templates/manageProduct.html
  app/templates/productDetails.html
Labels: enhancement, Back-end, Customer

#29 PMS page filter and search
  app/controllers/indexController.py
  app/controllers/productController.py
  app/models/Product.py
  app/routes/indexRoute.py
  app/routes/productRoute.py
  app/templates/index.html
  app/templates/manageProduct.html
Labels: enhancement, Back-end, Customer, Staff

#30 Designed the UI for userProfile
  app/static/css/style.css
  app/templates/userProfile.html
Labels: enhancement, Front-end, Customer, Staff, Admin

#31 [PMS] Publish/Withhold Product/Category
  app/controllers/indexController.py
  app/controllers/productController.py
  app/forms/NewProductForm.py
  app/models/Product.py
  app/models/ProductCategory.py
  app/routes/productRoute.py
  app/templates/manageProduct.html
  app/templates/productDetails.html
Labels: enhancement, Back-end, Staff

#32 User profile: button for update profile and change password
  app/controllers/userController.py
  app/models/User.py
  app/routes/userRoute.py
  app/templates/updateProfile.html
  app/templates/userProfile.html
Labels: enhancement, Front-end, Admin

#33 Designed the UI for productDetails
  app/static/js/productDetails.js
  app/templates/productDetails.html
Labels: Front-end, Customer, Staff
