Repository Ming119/110-1_Database-System_Project, pull requests merged in 2022-01, with the labels that each got.

#35 [Refactor] Add breadcrumb in all systems
  app/controllers/userController.py
  app/routes/userRoute.py
  app/templates/index.html
  app/templates/login.html
  app/templates/manageProduct.html
  app/templates/manageUser.html
  app/templates/newUser.html
  app/templates/register.html
Labels: enhancement, Front-end

#37 Fix Relation Between Product and Discount
  app/controllers/discountController.py
  app/controllers/indexController.py
  app/controllers/productController.py
  app/forms/NewDiscountForm.py
  app/forms/NewProductForm.py
  app/models/Discount.py
  app/models/Product.py
  app/models/ProductCategory.py
  app/routes/discountRoute.py
  app/static/css/js
  app/templates/index.html
  app/templates/manageDiscount.html
  app/templates/manageProduct.html
  app/templates/newDiscount.html
  app/templates/productDetails.html
  app/templates/updateDiscount.html
Labels: Back-end, Front-end, Customer, Staff, PMS, DMS

#40 Product Discount and Shipping Discount in SCMS
  app/controllers/discountController.py
  app/controllers/indexController.py
  app/models/Discount.py
  app/models/ShoppingCart.py
  app/models/User.py
  app/routes/indexRoute.py
  app/templates/base.html
  app/templates/index.html
  app/templates/newDiscount.html
  app/templates/productDetails.html
  app/templates/shoppingCart.html
Labels: Back-end, Front-end, Staff, PMS, DMS, SCMS

#41 Fix Issue #36
  app/controllers/indexController.py
  app/forms/RedeemCodeForm.py
  app/forms/__init__.py
  app/models/Discount.py
  app/static/js/shoppingCart.js
  app/templates/shoppingCart.html
Labels: Back-end, Front-end, Customer, Staff, PMS, DMS, SCMS

#42 [Refactor] Add count and fix filter in MMS, removed unused function
  app/controllers/discountController.py
  app/controllers/indexController.py
  app/controllers/userController.py
  app/models/Discount.py
  app/models/Product.py
  app/models/ProductCategory.py
  app/models/User.py
  app/templates/manageDiscount.html
  app/templates/manageUser.html
Labels: enhancement, Back-end, Admin

#43 [SCMS] Add New Address
  app/__init__.py
  app/controllers/indexController.py
  app/controllers/orderController.py
  app/controllers/userController.py
  app/forms/AddAddressForm.py
  app/forms/__init__.py
  app/models/CustomerAddress.py
  app/routes/__init__.py
  app/routes/orderRoute.py
  app/routes/userRoute.py
  app/templates/addAddress.html
  app/templates/base.html
  app/templates/forgotPassword.html
  app/templates/order/manageOrder.html
  app/templates/order/orderDeteail.html
  app/templates/resetPassword.html
  app/templates/shoppingCart.html
  app/templates/updateProfile.html
Labels: Back-end, Front-end, Customer, SCMS

#44 Finish Checkout
  app/controllers/indexController.py
  app/controllers/orderController.py
  app/forms/CheckoutForm.py
  app/forms/__init__.py
  app/models/Order.py
  app/models/ShoppingCart.py
  app/static/js/shoppingCart.js
  app/templates/base.html
  app/templates/shoppingCart.html
Labels: Back-end, Customer, OMS, SCMS

#45 [WIP] OMS front-end
  app/controllers/discountController.py
  app/controllers/indexController.py
  app/controllers/orderController.py
  app/controllers/productController.py
  app/controllers/userController.py
  app/models/Order.py
  app/models/Product.py
  app/routes/discountRoute.py
  app/routes/orderRoute.py
  app/templates/base.html
  app/templates/discount/manageDiscount.html
  app/templates/discount/newDiscount.html
  app/templates/discount/updateDiscount.html
  app/templates/index.html
  app/templates/login.html
  app/templates/order/manageOrder.html
  app/templates/product/manageProduct.html
  app/templates/product/productDetails.html
  app/templates/register.html
  app/templates/user/addAddress.html
  app/templates/user/manageUser.html
  app/templates/user/newUser.html
  app/templates/user/updateProfile.html
  app/templates/user/userProfile.html
Labels: Front-end, OMS, WIP

#46 [Refactor] Fix bugs
  app/controllers/indexController.py
  app/controllers/userController.py
  app/forms/checkout.py
  app/models/User.py
Labels: bug, Back-end, Customer, Admin, MMS

#53 CSMS
  app/controllers/orderController.py
  app/controllers/productController.py
  app/forms/__init__.py
  app/forms/comment.py
  app/models/Comment.py
  app/models/CustomerAddress.py
  app/models/Order.py
  app/models/User.py
  app/routes/order_route.py
  app/templates/index.html
  app/templates/mail/orderDelivered.html
  app/templates/order/orderDetails.html
  app/templates/product/manageProduct.html
  app/util.py
Labels: enhancement, Back-end, Customer, CSMS
